# nothing here
CONFIG_SDHC=y
CONFIG_SDHC_BCM2712=y
CONFIG_SDIO_STACK=y
CONFIG_LOG=y
CONFIG_SDHC_LOG_LEVEL_DBG=y
CONFIG_SD_LOG_LEVEL_DBG=y
CONFIG_MAX_XLAT_TABLES=24
CONFIG_GPIO=y

# Zephyr Shell configurations
CONFIG_SHELL=y
CONFIG_SHELL_BACKENDS=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_ARGC_MAX=10
CONFIG_SHELL_BACKEND_SERIAL_API_POLLING=y